config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :testtasks

  root 'testtasks#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :testtask
end

app/models/testtask.rb
class Testtask < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save

        #@testtask = Testtask.find(params[@comment.testtask_id])  #Testtask.find(params[@comment.testtask_id])
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        testtask = Testtask.find_by id: comment_params[:testtask_id]

        #redirect_to :testtasks_path
        format.html { redirect_to testtask_path(testtask), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :comment, :testtask_id)
    end
end

app/controllers/testtasks_controller.rb
class TesttasksController < ApplicationController
  before_action :set_testtask, only: [:show, :edit, :update, :destroy]

  # GET /testtasks
  # GET /testtasks.json
  def index
    @testtasks = Testtask.all
  end

  # GET /testtasks/1
  # GET /testtasks/1.json
  def show
  end

  # GET /testtasks/new
  def new
    @testtask = Testtask.new
  end

  # GET /testtasks/1/edit
  def edit
  end

  # POST /testtasks
  # POST /testtasks.json
  def create
    @testtask = Testtask.new(testtask_params)

    respond_to do |format|
      if @testtask.save
        format.html { redirect_to @testtask, notice: 'Testtask was successfully created.' }
        format.json { render :show, status: :created, location: @testtask }
      else
        format.html { render :new }
        format.json { render json: @testtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testtasks/1
  # PATCH/PUT /testtasks/1.json
  def update
    respond_to do |format|
      if @testtask.update(testtask_params)
        format.html { redirect_to @testtask, notice: 'Testtask was successfully updated.' }
        format.json { render :show, status: :ok, location: @testtask }
      else
        format.html { render :edit }
        format.json { render json: @testtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testtasks/1
  # DELETE /testtasks/1.json
  def destroy
    @testtask.destroy
    respond_to do |format|
      format.html { redirect_to testtasks_url, notice: 'Testtask was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testtask
      @testtask = Testtask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testtask_params
      params.require(:testtask).permit(:name, :tasktext, :created, :updated)
    end

  #
  #
  # #comments
  # # POST /comments
  # # POST /comments.json
  # def createComment
  #   @comment = Comment.new(comment_params)
  #
  #   respond_to do |format|
  #     if @comment.save
  #       format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
  #       format.json { render :show, status: :created, location: @comment }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # Never trust parameters from the scary internet, only allow the white list through.
  # def comment_params
  #   params.require(:comment).permit(:title, :comment, :testtask_id)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/testtasks_helper.rb
module TesttasksHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
    <%= f.hidden_field :testtask_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Comment</th>
      <th>Testtask</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.comment %></td>
        <td><%= comment.testtask %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Back', :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/testtasks/_form.html.erb
<%= form_for(@testtask) do |f| %>
  <% if @testtask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testtask.errors.count, "error") %> prohibited this testtask from being saved:</h2>

      <ul>
      <% @testtask.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Title'  %><br>
    <%= f.text_field :name, :class =>"textTitle" %>
  </div>
  <div class="field">
    <%= f.label 'Text'%><br>
    <%= f.text_area :tasktext, :maxlength => 255 %>
  </div>
 <!-- <div class="field">
    <%#= f.label :created %><br>
    <%#= f.datetime_select :created %>
  </div>
  <div class="field">
    <%#= f.label :updated %><br>
    <%#= f.datetime_select :updated_at %>
  </div>
  -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testtasks/edit.html.erb
<h1>Editing Testtask</h1>

<%= render 'form' %>

<%= link_to 'Show', @testtask %> |
<%= link_to 'Back', testtasks_path %>

app/views/testtasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing tasks</h1>

<table border="solid">
  <thead>
    <tr>
      <th width="200px">Task title</th>
      <th width="50%">Text</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @testtasks.each do |testtask| %>
      <tr>
        <td><%= testtask.name %></td>
        <td><%= testtask.tasktext %></td>
        <td><%= testtask.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= testtask.updated_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= link_to 'Show', testtask %></td>
        <td><%= link_to 'Edit', edit_testtask_path(testtask) %></td>
        <td><%= link_to 'Destroy', testtask, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New task', new_testtask_path %>

app/views/testtasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', testtasks_path %>

app/views/testtasks/show.html.erb
<h1>Task details</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @testtask.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @testtask.tasktext %>
</p>

<p>
  <strong>Created:</strong>
  <%= @testtask.created_at.strftime("%d/%m/%Y %H:%M") %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @testtask.updated_at.strftime("%d/%m/%Y %H:%M") %>
</p>

<%= link_to 'Edit', edit_testtask_path(@testtask) %> |
<%= link_to 'Back', testtasks_path %>

<br>
<h2>Comments</h2>

<table border="solid">
  <thead>
  <tr>
    <th width="200px">Comment title</th>
    <th width="50%">Comment</th>
    <th>Created</th>
    <th>Updated</th>
    <th colspan="3">Action</th>
  </tr>
  </thead>

  <tbody>
  <%  @testtask.comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.comment %></td>
        <td><%= comment.created_at.strftime("%d/%m/%Y %H:%M") %>
        <td><%= comment.updated_at.strftime("%d/%m/%Y %H:%M") %>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= form_for Comment.new do |f| %>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :comment %><br>
      <%= f.text_area :comment, :maxlength => 255 %>
    </div>
    <%= f.hidden_field :testtask_id, :value => @testtask.id %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>
<%#= link_to 'New Comment', new_comment_path(@testtask.id) %>

<!--
<p>
  <strong>Comments:</strong>
    <table>
        <thead>
            <tr>
                <th>title</th>
                <th>created</th>
                <th>Updated</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            <%# @testtask.testdetails.each do |testdetail| %>
                <tr>
                    <td><%#= testdetail.detailtext %></td>
                    <td><%#= testdetail.created_at %></td>
                    <td><%#= testdetail.updated_at %></td>
                    <td>'aaa'</td>
                </tr>
            <%# end %>
        </tbody>
    </table>
-->

</p>